
import com.example.memorygame.R
import com.example.model.ImageModel

class AlImages {
    val images = ArrayList<ImageModel>()
    fun addWords(): ArrayList<ImageModel> {

        // shu yerga hamma rasmlarni qushib chiqmamiz
        // bu bizga rasmlar listini beradi
        images.add(ImageModel(R.drawable.img_1))
        images.add(ImageModel(R.drawable.img_2))
        images.add(ImageModel(R.drawable.img_3))
        images.add(ImageModel(R.drawable.img_5))
        images.add(ImageModel(R.drawable.img_6))
        images.add(ImageModel(R.drawable.img_7))
        images.add(ImageModel(R.drawable.img_8))
        images.add(ImageModel(R.drawable.img_9))
        images.add(ImageModel(R.drawable.img_10))
        images.add(ImageModel(R.drawable.img_11))
        images.add(ImageModel(R.drawable.img_12))
        images.add(ImageModel(R.drawable.img_13))
        images.add(ImageModel(R.drawable.img_14))
        images.add(ImageModel(R.drawable.img_15))
        images.add(ImageModel(R.drawable.img_16))
        images.add(ImageModel(R.drawable.img_17))
        images.add(ImageModel(R.drawable.img_18))
        images.add(ImageModel(R.drawable.img_19))
        images.add(ImageModel(R.drawable.img_20))
        images.add(ImageModel(R.drawable.img_21))
        images.add(ImageModel(R.drawable.img_22))
        images.add(ImageModel(R.drawable.img_23))
        images.add(ImageModel(R.drawable.img_24))
        images.add(ImageModel(R.drawable.img_25))
        images.add(ImageModel(R.drawable.img_26))
        images.add(ImageModel(R.drawable.img_27))
        images.add(ImageModel(R.drawable.img_28))
        images.add(ImageModel(R.drawable.img_29))
        images.add(ImageModel(R.drawable.img_30))
        images.add(ImageModel(R.drawable.img_31))
        images.add(ImageModel(R.drawable.img_32))
        images.add(ImageModel(R.drawable.img_33))
        images.add(ImageModel(R.drawable.img_34))
        images.add(ImageModel(R.drawable.img_35))
        images.add(ImageModel(R.drawable.img_36))
        images.add(ImageModel(R.drawable.img_37))
        images.add(ImageModel(R.drawable.img_38))
        images.add(ImageModel(R.drawable.img_39))
        images.add(ImageModel(R.drawable.img_40))
        images.add(ImageModel(R.drawable.img_41))
        images.add(ImageModel(R.drawable.img_42))
        images.add(ImageModel(R.drawable.img_43))
        images.add(ImageModel(R.drawable.img_44))
        images.add(ImageModel(R.drawable.img_45))
        images.add(ImageModel(R.drawable.img_46))
        images.add(ImageModel(R.drawable.img_47))
        images.add(ImageModel(R.drawable.img_48))
        images.add(ImageModel(R.drawable.img_49))
        images.add(ImageModel(R.drawable.img_50))
        images.add(ImageModel(R.drawable.img_51))
        images.add(ImageModel(R.drawable.img_52))
        images.add(ImageModel(R.drawable.img_53))
        images.add(ImageModel(R.drawable.img_54))
        images.add(ImageModel(R.drawable.img_55))
        images.add(ImageModel(R.drawable.img_56))
        images.add(ImageModel(R.drawable.img_57))
        images.add(ImageModel(R.drawable.img_58))
        images.add(ImageModel(R.drawable.img_59))
        images.add(ImageModel(R.drawable.img_60))
        images.add(ImageModel(R.drawable.img_61))
        images.add(ImageModel(R.drawable.img_62))
        images.add(ImageModel(R.drawable.img_63))
        images.add(ImageModel(R.drawable.img_64))
        images.add(ImageModel(R.drawable.img_65))
        images.add(ImageModel(R.drawable.img_66))
        images.add(ImageModel(R.drawable.img_67))
        images.add(ImageModel(R.drawable.img_68))
        images.add(ImageModel(R.drawable.img_69))
        images.add(ImageModel(R.drawable.img_70))
        images.add(ImageModel(R.drawable.img_71))
        images.add(ImageModel(R.drawable.img_72))
        images.add(ImageModel(R.drawable.img_73))
        images.add(ImageModel(R.drawable.img_74))
        images.add(ImageModel(R.drawable.img_75))
        images.add(ImageModel(R.drawable.img_76))
        images.add(ImageModel(R.drawable.img_77))
        images.add(ImageModel(R.drawable.img_78))
        images.add(ImageModel(R.drawable.img_79))
        images.add(ImageModel(R.drawable.img_80))
        images.add(ImageModel(R.drawable.img_81))
        images.add(ImageModel(R.drawable.img_82))



        return images
    }
}